### ISSUE TITLE
Remove doc about pointer

### ISSUE THREAD

**Issue by Toinne** [be-hacking-hyf/javascript-2#2]
In these examples underneath you are copying the reference to the variable.

https://github.com/be-hacking-hyf/javascript-2/blob/f7628a07bcdfe7975f5044f9a9c73524d29d382c/week-1-project/practice-problems/arrays.js#L38

https://github.com/be-hacking-hyf/javascript-2/blob/7e294ad86ff5d9685df6f307d507ff0931c0abb2/week-2-project/practice-problems/objects.js#L37

Would avoid talking about pointers. Because a pointer refers to to a concept in C. Javascript does not really have an equivalent of that.

best explanation I could find https://medium.com/@naveenkarippai/learning-how-references-work-in-javascript-a066a4e15600

**Comment by Toinne** [comment]
Saying the reference "points to" something is fine for me.
But saying the reference is a pointer is incorrect I think.

**Comment by colevandersWands** [comment]
Correctness is always welcome
