### ISSUE TITLE
Week 1 practice problems add new array variables for each side effect test

### ISSUE THREAD

**Issue by Toinne** [be-hacking-hyf/javascript-2#3]
The problems e.g. with reusing `arr1` in each test is that if you make a mistake in 1 of them it has side effect in all.

Would maybe be very confusing for students and very demotivating.

https://github.com/be-hacking-hyf/javascript-2/blob/master/week-1-project/practice-problems/avoiding-side-effects.js#L177-L184

**Comment by colevandersWands** [comment]
True.  Side-effects across exercises would be unhelpful, they couldn't put one aside and come back to it later.
I'll go through and add separate arrays per exercises
