### ISSUE TITLE
Mistake in copying array ?

### ISSUE THREAD

**Issue by Toinne** [be-hacking-hyf/javascript-2#4]
Seems to me in order to complete the example should be 

```js
function mergeArrays(arr1, arr2) { 
   return [...arr1, ...arr2]; 
 } 
```

Instead of

https://github.com/be-hacking-hyf/javascript-2/blob/895a6085015ad7faa95de6b857d460caa077fbe0/week-1-project/practice-problems/functions-to-objects.js#L129-L131

**Comment by colevandersWands** [comment]
👍 .  fixed
