### ISSUE TITLE
Incorrect file and function names

### ISSUE THREAD

**Issue by Toinne** [be-hacking-hyf/javascript-2#7]
This file does not exist

https://github.com/be-hacking-hyf/javascript-2/blob/abb5bd9008a3eb046d59489c0fe56b51d9978a59/week-1-project/user-interface/index.html#L46

This function does not exist

https://github.com/be-hacking-hyf/javascript-2/blob/74822042b63c596500d727a4a838ff6a9400b018/week-1-project/user-interface/handlers/view-sorted-strings.js#L1

Probably referring to the `view-sorted-strings.js` file and `viewSortedStringsHandler` function

**Comment by colevandersWands** [comment]
pull request merged
